### ISSUE TITLE
Resolution going from 0 -> 8 for GeoCoord (0, 0)

### ISSUE THREAD

**Issue by lacasaprivata2** [rustyconover/libh3#2]
For the input (0, 0)

```
pub fn h3ids(lat: u64, lng: u64) -> Vec<String> {
  let geocoord = GeoCoord {
    lat: degs_to_rads((lat as f64) / 10_000_000f64),
    lon: degs_to_rads((lng as f64) / 10_000_000f64),
  };
  let mut ostream = vec![format!("{}-{}", 0, 0)];
  for resolution in 1..8 {
    let index = geo_to_h3(&geocoord, resolution - 1).unwrap();
    ostream.push(format!("{}-{}", resolution, index));
  }
  return ostream;
}

```

getting these values

In english, res from 0 -> 8, lng = lat = 0

"0-578536630256664575"
"1-583031433791012863"
"2-587531734883500031"
"3-592035265791393791"
"4-596538564771053567"
"5-601042424243945471"
"6-605546023066009599"

Any thoughts why that might be the case? I assume this isn't expected...

**Comment by rustyconover** [comment]
Hi there,

Why don’t you think this would be expected?  Geocoords change with each
resolution.

Rusty

**Comment by lacasaprivata2** [comment]
Probably a lack of knowledge on my end on H3 itseslf - i thought in H3 the indexes had the following bounds

Resolution	Average Hexagon Area (km2)	Average Hexagon Edge Length (km)	Number of unique indexes
0	          4,250,546.8477000	          1,107.712591000	                  122
1	          607,220.9782429	            418.676005500	                    842
2	          86,745.8540347	            158.244655800	                    5,882
3	          12,392.2648621	            59.810857940	                    41,162
4	          1,770.3235517	              22.606379400                    	288,122
5	          252.9033645	                8.544408276	                      2,016,842
6	          36.1290521	                3.229482772	                      14,117,882
7	          5.1612932	                  1.220629759	                      98,825,162
8	          0.7373276	                  0.461354684                     	691,776,122
9	          0.1053325	                  0.174375668                     	4,842,432,842
10	        0.0150475	                  0.065907807                     	33,897,029,882
11	        0.0021496	                  0.024910561                     	237,279,209,162
12	        0.0003071	                  0.009415526                       1,660,954,464,122
13	        0.0000439	                  0.003559893                     	11,626,681,248,842
14	        0.0000063	                  0.001348575	                      81,386,768,741,882
15	        0.0000009	                  0.000509713	                      569,707,381,193,162


why would there be an index for resolution 0 of 578536630256664575
